global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/prometheus.rules.yml

scrape_configs:
  - job_name: "mtogo-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
